all:
  children:
    proxmox_nodes:
      hosts:
        pve1:
          ansible_host: 192.168.1.10
          node_role: primary
        pve2:
          ansible_host: 192.168.1.11
          node_role: support
      vars:
        ansible_python_interpreter: /usr/bin/python3
